name: Trigger auto deployment for hello-world-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hello-world-app-AutoDeployTrigger-2bbd0468-a768-44ac-bb5e-3e707e85ce19.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLOWORLDAPP_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az acr build -t hello-world-app:${{ github.sha }} -r ${{ secrets.HELLOWORLD_ACR_SERVER }} .

      # - name: Log in to container registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: acrhelloworldj4urcwnjuloug.azurecr.io
      #     username: ${{ secrets.HELLOWORLDAPP_REGISTRY_USERNAME }}
      #     password: ${{ secrets.HELLOWORLDAPP_REGISTRY_PASSWORD }}

      # - name: Build and push container image to registry
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ${{ secrets.HELLOWORLD_ACR_SERVER }}/hello-world-app:${{ github.sha }}
      #     file: ./Dockerfile
      #     context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLOWORLDAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n hello-world-app -g hello-world-rg --server ${{ secrets.HELLOWORLD_ACR_SERVER }} --identity  ${{ secrets.HELLOWORLDAPP_DEPLOY_ID }}
            az containerapp update -n hello-world-app -g hello-world-rg --image ${{ secrets.HELLOWORLD_ACR_SERVER }}/hello-world-app:${{ github.sha }}
